### ISSUE TITLE
how to?

### ISSUE THREAD

**Issue by Hackerman-825** [rdebath/viruses#1]
how do i use Virus Creation Laboratory?

is it safe if i unzip and run the VCL.exe?

what happens if i run VCL.exe

**Comment by V01D-NULL** [comment]
You should be using a VM

**Comment by rdebath** [comment]
To reiterate, you should be using a Windows 95 VM. I suggest W95 for that because of compatibility.

The VCL program is supposed to be a simple way of creating cookie-cutter viruses. AFAIR it's not in itself malicious, but it does contain code that is just one step away from being so. Routines are included to do several data corruption and disk wiping tasks. There's also a "random port write" routine that's been known to damage physical hardware, but on a modern OS, even W95, should just segfault.

I just checked though, my windows AV might have it whitelisted; or it's relying on a heuristic/activity check.

**Comment by V01D-NULL** [comment]
Well this repo should only be accessed by people who know what they are doing.

Rule of thumb: Dont run executables you dont trust and haven't verified.

Always use a VM, if that isn't possible and you really have to run it use https://www.hybrid-analysis.com/

Honestly this is pretty basic stuff, and the VM needs to be correctly configured too so I suggest you dont touch anything inside of this repo for your (own - Depends on how much you rely on that computer for daily tasks like school or work or something) computers safety

**Comment by V01D-NULL** [comment]
> To reiterate, you should be using a Windows 95 VM. I suggest W95 for that because of compatibility.
> 
> The VCL program is supposed to be a simple way of creating cookie-cutter viruses. AFAIR it's not in itself malicious, but it does contain code that is just one step away from being so. Routines are included to do several data corruption and disk wiping tasks. There's also a "random port write" routine that's been known to damage physical hardware, but on a modern OS, even W95, should just segfault.
> 
> I just checked though, my windows AV might have it whitelisted; or it's relying on a heuristic/activity check.
> 

So....
You gonna close the issue🙈?

**Comment by rdebath** [comment]
:horse_racing: Just giving them a little time to respond.
